# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c6752c84370092d790e133b3783a8f546e6deac662c859db6aa9a4c65e3d289b10aeae1971b192e7a90c48242ebac86727325eb7e726cfc17176b3406007d04

test:
  secret_key_base: 40edde2999bc1282be6b8d4467e79bd767e8b3cd892a623bdda241d872c3b5e42413afa229733e2aaaf20e6db926636bc35cefeecc373c2452ff44c3e012f5d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
